version: '3.9'

services:  
  authentication-db:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    image: khalld/authentication-db:latest
    restart: unless-stopped
    ports:
      - '23306:3306'
    expose:
      # Opens port 23306 on the container
      - '23306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - authentication-db-network
    container_name: authentication-db

networks: 
  authentication-db-network:
    name: authentication-db-network